repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    # -   id: check-added-large-files

    # Ruff version. ( Linting )
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.290
    hooks:
      - id: ruff
        args: ["--fix"]

    # Black (Formating)
-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black

    # Mypy mirror ( Static type checking)
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        args: [--strict, --ignore-missing-imports]
